
auth.token=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

defaults.org=bns-enterprises-2b
defaults.project=ngoconnect-app

defaults.url=https://sentry.io/
